# Generated by Django 3.2.16 on 2022-11-05 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение - 1')], verbose_name='Количество ингредиента'),
        ),
    ]
